config/routes.rb
Site::Application.routes.draw do

  root :to => 'home#index'

  match 'contato' => "contato#index"
  match 'sobre' => "sobre#index"
  post 'contato/send_mail' => "contato#send_mail"
  match 'produtos' => "produtos#index"

end

app/models/message.rb
class Message
	include ActiveModel::Validations
	include ActiveModel::Conversion
	extend ActiveModel::Naming


	attr_accessor :name, :email, :content

	validates_presence_of :name, :email, :content
	validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
	validates_length_of :content, :maximum => 500

	def initialize(attributes = {})
		attributes.each do |name, value|
			send("#{name}=", value)
		end
	end

	def persisted?
		false
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contato_controller.rb
class ContatoController < ApplicationController

	def index
		@message = Message.new
		render 'index'
	end

	def send_mail
		@message = Message.new(params[:message])
	
		if @message.valid?
      		Contato.send_mail( @message ).deliver
      		flash[:notice] = "Sua mensagem foi enviada! Obrigado por entrar em contato."
      		redirect_to :action => 'index'
  		else
  			render :action => 'index'
  		end
  	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

	def index
	end
end

app/controllers/sobre_controller.rb
class SobreController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def mark_required(object, attribute)
		"*" if object.class.validators_on(attribute).map(&:class).include? ActiveModel::Validations::PresenceValidator
	end

	def flash_class(level)
		case level
		when :notice then "info"
		when :error then "error"
		when :alert then "warning"
		end
	end
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sobre_helper.rb
module SobreHelper
end

app/views/contato/index.html.erb
<% @active_page = 'contato' %>

<% content_for :head do %>
  Contato
<% end %>

<div class="banner featured">
	<div class="container welcome">
	<h1 class="title">Contato</h1>	
	<h2>
		Deixe seu recado ou sugestão
	</h2>
	
	</div>
</div>

<div class="container container-padding">

	<div class="row">

		<div class="span4">
			<div class="well">
			<h2>Endereço</h2>
			<address>		
			 	Av. Santo Fregonese, 1666, bairro Industrial<br/>
			 	<strong>FINDEX/ACEFB</strong><br/>
			 	Francisco Beltrão, PR<br/>
			 	<abbr title="Telefone">Fone:</abbr> (46) 9111-7060
			</address>

			<address>
			  <strong>Email</strong><br>
			  Ulisses Constantini <a href="mailto:ulisses@parseint.com.br">ulisses@parseint.com.br</a><br/>
			  Financeiro <a href="mailto:administrativo@parseint.com.br">administrativo@parseint.com.br</a>
			</address>

			<address>
			  <strong>Skype</strong><br>
			  ulisses.constantini<br/>
			</address>
			</div>
		</div>

		<div class="span8">

			<%= render :partial => "/layouts/flash", locals: { flash: flash }  %>
			<%= form_for(@message, :url => contato_send_mail_path, :html => {:class => "form-horizontal"}) do |f| %>


			<div class="control-group">
				<div class="controls">
					<% @message.errors.full_messages.each do |msg| %>
					<p><%= msg %></p>
					<% end %>
				</div>
			</div>


			<div class="control-group">
				<%= f.label :name, "Nome #{mark_required(@message, :name)}", :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :name, :class => "input-xlarge"  %>
				</div>
			</div>

			<div class="control-group">
				<%= f.label :email, "E-mail #{mark_required(@message, :email)}", :class => "control-label"  %>
				<div class="controls">
					<%= f.text_field :email, :class => "input-xlarge"  %>
				</div>
			</div>

			<div class="control-group">
				<%= f.label :content, "Mensagem #{mark_required(@message, :content)}", :class => "control-label"  %>
				<div class="controls">
					<%= f.text_area :content, :rows => "5", :class => "input-block-level" %>
				</div>
			</div>

			<div class="control-group">
				<div class="controls">
					<%= f.submit "Enviar", :class => "btn btn-warning"%>
				</div>
			</div>

			<% end %>

		</div>

		
	</div>

</div>

app/views/home/index.html.erb
<% @active_page = 'inicio' %>

<div class="banner featured">
	<div class="container welcome">
	<h1 class="title">Desenvolvemos soluções através de software</h1>	
	<h2>
		Somos apaixonados por software e amamos desenvolver <span class="hue_block">soluções</span> 
		simples e práticas
	</h2>
	<h4 class="text-right"><a href="#">conheça nossos produtos</a></h4>
	</div>
</div>

<div class="container container-padding">
	

	<div id="sisagilCarousel" class="carousel slide">
		
		<div class="carousel-inner">
			 <ol class="carousel-indicators">
			    <li data-target="#sisagilCarousel" data-slide-to="0" class="active"></li>
			    <li data-target="#sisagilCarousel" data-slide-to="1"></li>
			    <li data-target="#sisagilCarousel" data-slide-to="2"></li>
			  </ol>
			<div class="active item">
				 <div class="row">
					<div class="span6">
						<h4>Conheça o Sisagil</h4>
						<p>
						Sistema de gerenciamento empresarial e emissão de NF-e para pequenas e
						médias empresas.
						</p>
						<p>O melhor custo/benefício do mercado.</p>
						<p>Totalmente Web.</p> <p>Simples e fácil.</p>
						
						<br/>
						
						<a href="http://sisagil.com/sobre" target="_blank">Mais detalhes</a>
						
					</div>
					<div class="span6">
						<img src="/assets/banner/ipads-sisagil.png" class="img-polaroid"/>
					</div>
				 </div>
			</div>
			<div class="item">
				 <div class="row">
					<div class="span6">sdads</div>
					<div class="span6">sdads</div>
				 </div>
			</div>
			<div class="item">
				<div class="row">
					<div class="span6">sdads</div>
					<div class="span6">sdads</div>
				 </div>
			</div>
		</div>
		
	</div>

</div>


<div class="banner">
	<div class="container">
	<h2>O que dizem nossos clientes</h2>

	<div id="myCarousel" class="depoimentos carousel slide">

		<!-- Carousel items -->
		<div class="carousel-inner">
			 <ol class="carousel-indicators">
			    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
			    <li data-target="#myCarousel" data-slide-to="1"></li>
			    <li data-target="#myCarousel" data-slide-to="2"></li>
			  </ol>
			<div class="active item">
				<blockquote>
				  <p>A Zangraf Digital Fotolivro buscou na Parseint uma parceria ágil, criativa e de qualidade no desenvolvimento de Software sob demanda.</p>
				  <small>Marcelo Pedrazzani | <cite title="Empresa">Zangraf Digital</cite></small>
				</blockquote>

			</div>
			<div class="item">
				<blockquote>
				  <p>Estou bastante contente com as continuas evoluções. Todas as pendências sempre foram resolvidas de forma rápida e eficiente. O Sisagil com certeza é o melhor de todos.</p>
				  <small>Anilda Trento | <cite title="Empresa">Magazine Renascença</cite></small>
				</blockquote>
			</div>
			<div class="item">
				<blockquote>
				  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
				  <small>Someone famous <cite title="Source Title">Source Title</cite></small>
				</blockquote>
			</div>
		</div>
		
	</div>


	</div>
</div>



<script type="text/javascript">
	$(function() {
		$('#myCarousel').carousel({interval: 8000, cycle: true});
		//$('#sisagilCarousel').carousel({interval: 4000, cycle: true});
		
	});
</script>

app/views/layouts/_flash.html.erb
<% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="alert <%= flash_class(level) %>">
      <a class="close" href="#">×</a>
      <%= content_tag :p, flash[level] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:head).empty? ? "Parseint - Desenvolvimento Web | Mobile" : yield(:head) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
	<div class="container">
		<div class="logo">
			<a href="/">
				Logo
			</a>
		</div>

		<div class="menu">
		<ul class="nav nav-pills pull-right">
		  <li class="<%= @active_page == 'inicio' ? 'active' : '' %>">
		    <a href="/">Início</a>
		  </li>
		  <li class="<%= @active_page == 'produtos' ? 'active' : '' %>"><a href="/produtos">Produtos</a></li>
		  <li class="<%= @active_page == 'sobre' ? 'active' : '' %>"><a href="/sobre">Sobre</a></li>
		  <li class="<%= @active_page == 'contato' ? 'active' : '' %>"><a href="/contato">Contato</a></li>
		</ul>
		</div>

	</div>
</div>

<div class="wrap">

		<%= yield %>

	<div id="push"></div>
</div>

<div id="footer">
	<div class="container">
		<p class="credit">Parseint - Desenvolvimento Web | Mobile</p>
	</div>
</div>


 

</body>
</html>

app/views/produtos/index.html.erb
<% @active_page = 'produtos' %>

<% content_for :head do %>
  Produtos
<% end %>


<div class="banner featured">
	<div class="container welcome">
	<h1 class="title">Produtos</h1>	
	<h2>produtos?</h2>
	
	</div>
</div>

<div class="banner">
	<div class="container">
	<h4>
		 Somos uma pequena empresa apaixonada por desenvolver software e principalmente entregar soluções. Temos como objetivo criar sistemas web e mobile.
	</h4>
	</div>
</div>



<div class="container container-padding">

	<div class="row">

		<div class="span6">
			<a href="images/fullscreen/2.jpg" rel="prettyPhoto" title="This is the description">
				<img src="images/thumbnails/t_2.jpg" width="60" height="60" alt="This is the title" />
			</a> 
		</div>
		<div class="span6">
			<div class="well">opa</div> 
		</div>
	</div>

</div>

app/views/sobre/index.html.erb
<% @active_page = 'sobre' %>

<% content_for :head do %>
  Sobre
<% end %>


<div class="banner featured">
	<div class="container welcome">
	<h1 class="title">Sobre a Parseint</h1>	
	<h2>Quem somos?</h2>
	
	</div>
</div>

<div class="banner">
	<div class="container">
	<h4>
		 Somos uma pequena empresa apaixonada por desenvolver software e principalmente entregar soluções. Temos como objetivo criar sistemas web e mobile.
	</h4>
	</div>
</div>

<div class="container container-padding">
	<%= render :partial => "/layouts/flash", locals: { flash: flash }  %>
	
	<div class="row">
		<div class="span4">
			<h2>Nossa Visão</h2>
			<p>Transformar a marca parseInt em sinônimo de agilidade e inovação na área de Desenvolvimento de Software.</p>
		</div>

		<div class="span4">
			<h2>Nossa Missão</h2>
			<p>A missão da ParseInt é seguir Metodologias Ágeis de Desenvolvimento de Software, focar nas funcionalidades tecnológicas, simplificar a vida das pessoas, melhorar o desempenho empresarial, reduzir custos e gerir produtos de qualidade.</p>
		</div>

		<div class="span4 well">
		<h2>Onde fica?</h2>
			<address>
			 	<strong>Parseint Desenvolvimento de Sistemas Ltda</strong><br/><br/>
			 	Av. Santo Fregonese, 1666, bairro Industrial<br/>
			 	<strong>FINDEX/ACEFB</strong><br/>
			 	Francisco Beltrão, PR<br/>
			 	<abbr title="Telefone">Fone:</abbr> (46) 9111-7060
			</address>

		</div>


	</div> 

</div>